### ISSUE TITLE
any info for acs?

### ISSUE THREAD

**Issue by tinysun** [meh301/HG8045Q#11]
the root can read acs info? I need it

**Comment by SambasOnFire** [comment]
<ManagementServer EnableCWMP="0" URL="http://huawei-hg8045d_01.mv-acs.jp:55443" Username="huawei-admin" Password="$1Q2k&gt;%d^;+Q[xFL/OUy-L@!!!$"

**Comment by tinysun** [comment]
> <ManagementServer EnableCWMP="0" URL="http://huawei-hg8045d_01.mv-acs.jp:55443" Username="huawei-admin" Password="$1Q2k>%d^;+Q[xFL/OUy-L@!!!$"

thanks

**Comment by SambasOnFire** [comment]
password=huawei_12345
