### ISSUE TITLE
Bridge setting persists?

### ISSUE THREAD

**Issue by pkishino** [meh301/HG8045Q#5]
Hello,
I'm on Nuro and sadly didnt see this before the firmware updated and master account is locked :/
Anyway, I was curious for those who did manage to enable bridge mode, did this persist after later firmware upgrade?has nuro patched this? Cause we might be moving and considering to close the current account (on wifes name) and start a new one with the kakaku cashback campaign and perhaps get a new huawei router that HASN't been patched yet and enable it locally first before it has time to update fw..?

**Comment by meh301** [comment]
Yes, the bridge mode persisted. You can actually just use another Huawei ONT like the Huawei MA5671 which is fully unlocked and can authorize itself on the nuro network.

**Comment by pkishino** [comment]
Hmm, Google and doesn’t seem so expensive to get one. So it’s just plug and play? No need for any special settings or such? 
that would be nice

**Comment by meh301** [comment]
For the moment, the only settings required is writing in the serial number printed on the back of the nuro ONT as the authentication password in your own ONT. This may or may not change depending on if Nuro doesn't like it though.

**Comment by pkishino** [comment]
Apart from AliExpress, any other decent source for the ont?

**Comment by meh301** [comment]
Not that I know of...

**Comment by li-yifei** [comment]
Hello,
I enabled bridge mode on my HG8045Q yesterday before NURO revoked the master password, and it works.
But I'm trying to change some settings not yet applied.
I wonder if the master password would be reset if I reset the whole device without fiber connection?
Thank you
